### ISSUE TITLE
**[BUG]**

### ISSUE THREAD

**Issue by aledthom** [CGCookie/retopoflow#1211]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.3

Blender Version/Hash: 3.1

Platform Version/Distribution: xubuntu

&nbsp;

**Issue:**

hitting "new target" (either one) and this error comes up, then changes to "retopoflow BROKEN"
tried reinstall, happens with any mesh even just the basic cube

CookieCutter_Exceptions: handling caught exception
    action: initialize internals (Exception Callbacks, FSM, UI, Actions)
____________________________________________________________________________________________________
Exception Info
- Time: 2023-04-17 22:34:38.811269
- Count: 1
- Hash: 6947ecb110ea88499719261ab84d3458
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'KeyMapItem' object has no attribute 'direction'
  -     .../common/useractions.py
  - 000 0148:<setcomp>() kmi.direction == 'ANY'
  - 001 0142:blenderop_to_kmis() return {
  - 002 0156:blenderop_to_actions() for kmi in cls.blenderop_to_kmis(blenderop)
  - 003 0714:<setcomp>() for action in Action.blenderop_to_actions(blenderop)
  - 004 0711:__init__() self.keymap[group_name] |= {
  - 005 0685:get_instance() Actions._instance = Actions(context)
  - 006 1067:__init__() ActionHandler._actions = Actions.get_instance(context)
  -     .../common/ui_document.py
  - 007 0127:init() self.actions = ActionHandler(context, UI_Document.default_keymap)
  -     .../cookiecutter/cookiecutter_ui.py
  - 008 0080:_cc_ui_init() self.document.init(self.context)
  -     .../cookiecutter/cookiecutter_modal.py
  - 009 0087:modal_init_cc_internals() self._cc_ui_init()
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 010 0036:try_exception() yield
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'KeyMapItem' object has no attribute 'direction'
RF_UI.handle_exception: 'KeyMapItem' object has no attribute 'direction'
Info: Total files 0 | Changed 0 | Failed 0
Info: Saved "RetopoFlow_backup_EMERGENCY.blend"
CookieCutter caught exception while calling back exception callbacks: handle_exception
____________________________________________________________________________________________________
Exception Info
- Time: 2023-04-17 22:34:38.882759
- Count: 2
- Hash: 81cc154c16e469e34499df5083bea9d7
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute '_undostack'
  -     /opt/blender/3.1/scripts/modules/bpy_types.py
  - 000 0772:__getattribute__() return super().__getattribute__(attr)
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_undo.py
  - 001 0092:undo_stack_actions() return self._undostack.keys()
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui_alert.py
  - 002 0266:alert_user() undo_stack_actions = self.undo_stack_actions() if hasattr(self, 'undo_stack_actions') else []
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui.py
  - 003 0063:handle_exception() self.alert_user(title='Exception caught', message=message, level='exception', msghash=h)
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 004 0057:_callback_exception_callbacks() fn(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GitHub: Not reported, yet

&nbsp;

**How to Reproduce:**

select any mesh, create new target

**Comment by vxlcoder** [comment]
Thanks for the report, @aledthom.

This should be fixed in v3.3.1, which is not yet released.  You can try downloading an alpha version from https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0 (temp link)

**Comment by aledthom** [comment]
unfortunately seems to be still having the same problem and same exception

CookieCutter_Exceptions: handling caught exception
    action: initialize internals (Exception Callbacks, FSM, UI, Actions)
____________________________________________________________________________________________________
Exception Info
- Time: 2023-04-18 23:07:36.930315
- Count: 1
- Hash: 6947ecb110ea88499719261ab84d3458
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'KeyMapItem' object has no attribute 'direction'
  -     .../common/useractions.py
  - 000 0148:<setcomp>() kmi.direction == 'ANY'
  - 001 0142:blenderop_to_kmis() return {
  - 002 0156:blenderop_to_actions() for kmi in cls.blenderop_to_kmis(blenderop)
  - 003 0715:<setcomp>() for action in Action.blenderop_to_actions(blenderop)
  - 004 0712:__init__() self.keymap[group_name] |= {
  - 005 0686:get_instance() Actions._instance = Actions(context)
  - 006 1068:__init__() ActionHandler._actions = Actions.get_instance(context)
  -     .../common/ui_document.py
  - 007 0127:init() self.actions = ActionHandler(context, UI_Document.default_keymap)
  -     .../cookiecutter/cookiecutter_ui.py
  - 008 0080:_cc_ui_init() self.document.init(self.context)
  -     .../cookiecutter/cookiecutter_modal.py
  - 009 0087:modal_init_cc_internals() self._cc_ui_init()
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 010 0036:try_exception() yield
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'KeyMapItem' object has no attribute 'direction'
RF_UI.handle_exception: 'KeyMapItem' object has no attribute 'direction'
Info: Total files 0 | Changed 0 | Failed 0
Info: Saved "RetopoFlow_backup_EMERGENCY.blend"
CookieCutter caught exception while calling back exception callbacks: handle_exception
____________________________________________________________________________________________________
Exception Info
- Time: 2023-04-18 23:07:37.001446
- Count: 2
- Hash: 81cc154c16e469e34499df5083bea9d7
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute '_undostack'
  -     /opt/blender/3.1/scripts/modules/bpy_types.py
  - 000 0772:__getattribute__() return super().__getattribute__(attr)
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_undo.py
  - 001 0092:undo_stack_actions() return self._undostack.keys()
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui_alert.py
  - 002 0266:alert_user() undo_stack_actions = self.undo_stack_actions() if hasattr(self, 'undo_stack_actions') else []
  -     /home/aled/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rf/rf_ui.py
  - 003 0063:handle_exception() self.alert_user(title='Exception caught', message=message, level='exception', msghash=h)
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 004 0057:_callback_exception_callbacks() fn(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GitHub: Already reported!

**Comment by vxlcoder** [comment]
oh dear! that zip wasn't the latest.  sorry about that!

try it again (same link, but different zip).

https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0

**Comment by aledthom** [comment]
ah ok, yes it's doing something now, thanks for the prompt reply!
