### ISSUE TITLE
PolyStrips: Crash when creating corner while merging into existing geometry

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1490]
Blender can fully crash if you draw a strip with a corner onto another strip. Here are some examples, one in Blender 4.3 and one in Blender 4.4:

![Image](https://github.com/user-attachments/assets/395f0454-aa0c-4a6a-ab1a-aa30a20c2587)

![Image](https://github.com/user-attachments/assets/535eacd0-05b4-41e0-89a1-e6bd389f41f7)

```
RFCore.register
RFCore_Operator.__init__
CACHING BVHS FOR ALL SOURCE OBJECTS
  0.00secs
RFCore_Operator executing
Activating <class 'bl_ext.vscode_development.retopoflow.retopoflow.rfoverlays.quadstrip_selection_overlay.RFOperator_PolyStrips_Selection_Overlay'>
<bpy_struct, Area at 0x00000282EFEE6880> <bpy_struct, Region at 0x00000282EFEEBC20>
RFOperator_PolyStrips_Insert.execute: Caught Exception division by zero
____________________________________________________________________________________________________
Exception Info
- Time: 2025-04-01 19:56:25.895832
- Count: 1
- Hash: 96d54cf4e057eb721689d9195ab845e8
- Info:
  - EXCEPTION (<class 'ZeroDivisionError'>): division by zero
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips_logic.py
  - 000 0341:<listcomp>() find_point_at(stroke3D_local, self.is_cycle, (i / (nsamples - 1)))
  - 001 0340:create() samples = [
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips.py
  - 002 0227:execute() logic.create(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7AFFE960F
Module  : blender.exe
Thread  : 000259f0
Writing: C:\Users\Jonathan\AppData\Local\Temp\blender.crash.txt
```

**Comment by vxlcoder** [comment]
should work now!

**Comment by jlampel** [comment]
This is much better! I can still get a crash, but it is in an extremely specific scenario. It happens when you make this exact shape, where the stroke looks like it bounces off of the top edge:

![Image](https://github.com/user-attachments/assets/90a24955-07e1-4129-8ed1-46c6da694fcf)

It's a nonsense shape that I don't think anyone would make on purpose, but it could still happen.

**Comment by jlampel** [comment]
This appears to be fixed now! I think in 1f9dbe8f45efaa42d1cadb9209679a8a9600408c

**Comment by jlampel** [comment]
Whoops, sorry, that was a little premature. I didn't trigger it after several attempts, saw a PS change, and figured it was good. But I can still cause the crash after enough tries.

**Comment by vxlcoder** [comment]
should be fixed now!

**Comment by jlampel** [comment]
This works a vast majority of the time, significantly better than before, though I did just get it to crash once with the same "draw into a quad and end on the quad next to it" pattern. Will continue testing to see if there's anything else that can trigger it or if I can narrow down when it happens. 

```
RFOperator_PolyStrips_Insert.execute: Caught Exception list index out of range
____________________________________________________________________________________________________
Exception Info
- Time: 2025-04-09 11:22:51.778343
- Count: 1
- Hash: a2ab089ae6ae351c3ed7c35539288b80
- Info:
  - EXCEPTION (<class 'IndexError'>): list index out of range
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\common\bmesh_maths.py
  - 000 0053:find_point_at() if v <= 0: return points[0]
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips_logic.py
  - 001 0351:<listcomp>() find_point_at(stroke3D_local, self.is_cycle, (i / (nsamples - 1)))
  - 002 0350:create() samples = [
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips.py
  - 003 0229:execute() logic.create(context)
 ```

Any ideas why this results in a hard crash instead of just an error?

**Comment by vxlcoder** [comment]
i'm not sure why there's a hard crash, but 6b560d3 should work around this issue.  can you see if you can replicate it again??

**Comment by jlampel** [comment]
This took many, many tries of hammering at the exact pattern, but I did get one more:

```
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
ERROR: stroke totally inside the hovered face on snap1
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
RFOperator_PolyStrips_Insert.execute: Caught Exception float division by zero
____________________________________________________________________________________________________
Exception Info
- Time: 2025-04-09 17:53:41.983739
- Count: 1
- Hash: 7a06d63f69ad65e8c3a748aff14bbca5
- Info:
  - EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips_logic.py
  - 000 0130:warp_stroke() scale = es / ss
  - 001 0323:create() stroke3D_local = warp_stroke(
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips.py
  - 002 0231:execute() logic.create(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6057726CF
Module  : blender.exe
Thread  : 00064ad4
Writing: C:\Users\Jonathan\AppData\Local\Temp\blender.crash.txt
```

At this point though, it's such a specific scenario that I think we can put out a new build tomorrow regardless.

**Comment by jlampel** [comment]
I managed to get another one, this time going back to the `IndexError` rather than the `ZeroDivisionError`. Same pattern, draw into a quad and end on the one next to it

```
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
<class 'bl_ext.vscode_development.retopoflow.retopoflow.rftool_polystrips.polystrips.RFOperator_PolyStrips_Edit'>.poll: cls.can_start(context)=None
RFOperator_PolyStrips_Insert.execute: Caught Exception list index out of range
____________________________________________________________________________________________________
Exception Info
- Time: 2025-04-10 09:25:04.121926
- Count: 1
- Hash: 10d41d1743b9acdc7a3e684687161f16
- Info:
  - EXCEPTION (<class 'IndexError'>): list index out of range
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips_logic.py
  - 000 0323:create() if (stroke3D_local[0] - stroke3D_local[-1]).length == 0:
  -     C:\Users\Jonathan\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\vscode_development\retopoflow\retopoflow\rftool_polystrips\polystrips.py
  - 001 0231:execute() logic.create(context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF6057726CF
Module  : blender.exe
Thread  : 00062e6c
Writing: C:\Users\Jonathan\AppData\Local\Temp\blender.crash.txt
```

**Comment by serijn441** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by vxlcoder** [comment]
possibly fixed?

**Comment by vxlcoder** [comment]
any chance you can capture it in a video?

**Comment by jlampel** [comment]
Sure thing. I really can't figure out why it happens on some strokes and not others. 

Blender 4.4:
https://github.com/user-attachments/assets/d42ffb7d-1fd2-4020-af65-8969a5c0d1ef

Blender 4.3:
https://github.com/user-attachments/assets/03a5e892-7974-484a-b753-b137e3282856

**Comment by jlampel** [comment]
After a few good minutes of trying the same thing that broke it before, I can no longer reproduce this after the latest change. I will keep an eye out for it just in case, but I think we can close this out!
