### ISSUE TITLE
Options panel doesn't auto-adapt width

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#751]
The Options panel does not seem to adapt it's width (or content wrap) to fit. Rather it slides behind the viewport border. 

Screen recording: https://share.getcloudapp.com/Apuy5nDb

**Comment by carter2422** [comment]
For this one I'd prefer we use a fixed-width and wrap the content as needed. 

In this specific case it actually seems to be the decimal accuracy (20 digits!) on Symmetry `Threshold` that's causing the wide width.

**Comment by vxlcoder** [comment]
that was an issue with retina/ui scaling.  this should be fixed now!

**Comment by carter2422** [comment]
I think this is still an issue. Or perhaps it's a separate root cause, but my Options panel always starts underneath the viewport and only adjusts if I move it.
<img width="276" alt="Screen Shot 2019-11-27 at 8 27 51 PM" src="https://user-images.githubusercontent.com/1648631/69772055-7b31ae80-1154-11ea-9994-8c0981ddd952.png">

**Comment by jlampel** [comment]
This appears to have been fixed since, but definitely reopen if it continues to be an issue in v3.0+
