### ISSUE TITLE
[BUG] Target polycount warning appearing when there is no target

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#895]
The 'Target mesh is > 20k' warning displays in the RF dropdown when you exit RF, head to Object Mode, delete the target you just created, and select the source without entering Edit Mode. One way around this could be to only check the target polycount while in Edit Mode. 

Here's a file to test it with: https://www.dropbox.com/s/gsk8khvpu8mfjkq/viking-sculpt.blend?dl=0

![image](https://user-images.githubusercontent.com/12982300/100260219-02e40180-2efe-11eb-83ba-d8adc0e6af42.png)

**Comment by jlampel** [comment]
Actually, it appears that it's using the selected object as the target in Object Mode all the time, which means that if there is only one mesh in the scene it will say there's no source and will not let you start:

![image](https://user-images.githubusercontent.com/12982300/100261009-04fa9000-2eff-11eb-9bd6-d94889b17960.png)

This is on the latest build of master btw.

**Comment by vxlcoder** [comment]
should be fixed now

**Comment by jlampel** [comment]
I'm still getting 'No sources detected' in the default scene

**Comment by jlampel** [comment]
The target mesh warning is confirmed fixed though

**Comment by jlampel** [comment]
Fixed with https://github.com/CGCookie/retopoflow/commit/02a3a367109f013aff47ff936fd7340e8c5117b7 !
